# Generated by Django 3.0.1 on 2019-12-18 13:53

from django.db import migrations, models
import django.db.models.deletion


def create_object(apps, schema_editor):
    AnotherKey = apps.get_model('app', 'AnotherKey')
    Value = apps.get_model('app', 'Value')

    k = AnotherKey.objects.create(name='c')

    for v in Value.objects.all():
        v.another_key = k
        v.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='value',
            name='another_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.AnotherKey'),
        ),
        migrations.RunPython(create_object, migrations.RunPython.noop),
    ]
